#!/bin/bash

read word
read num

re='^[0-9]+$'
if ! [[ $num =~ $re ]] ; then
echo "error not a number" >&2; exit 0
fi

if [[ $word != "exit" ]]
then
echo "uncorrect arg"
elif ! [ -z $num ] 
then
echo $num
exit $num
else
echo "0"
exit 0
fi


