#!/bin/bash
read arg
if [[ $arg != "help" ]]
then
echo "write correct arg - help"
echo 1
exit 1

else 
echo "I will show u all moves and keys: "
echo '1. calc (sum/sub/mul/div; $num1; $num2)'
echo '2. search ($reg)'
echo '3. reverse ($file1; $file2)'
echo '4. strlen ($str)'
echo '5. '
echo '6. exit ($word; $num)'
echo '7. help ($arg)'
echo '8. interactive ()'
fi
